name: Build

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['ubuntu-latest', 'macos-latest']

    steps:
    - uses: actions/checkout@v3
    - uses: fwal/setup-swift@v1
      if: matrix.os != 'macos-latest'
      with:
        swift-version: '5.7'
    - name: Build
      run: swift build
    - name: Test
      run: swift test
